---
title: "Neuro Final"
author: ""
date: "3/17/22"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r packages, include=FALSE}
library(tidyverse)
library(tidymodels)
library(viridis)
```

```{r load-packages}
recognition = read_csv("Final Experiment Data.csv")
```


```{r mean-distrators}
recognition %>%
  group_by(Distractors) %>%
  summarize(mean_per_distractor = mean(Time))
```
As distractors increase, mean reaction time increases until 16...

```{r rt-by-distractors}
recognition %>%
# filter(Emotion == "Happy" | Emotion == "Sad") %>%
  ggplot(mapping = aes(x = Distractors, y = Time, 
                                           color = Emotion)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) + 
  labs(title = "Reaction Time by Number of Distractors", 
       subtitle = "All Subjects", y = "Reaction time in Seconds")
```

```{r}
recognition %>%
  ggplot(data = recognition, mapping = aes(x = Distractors, y = Time, 
                                           color = Emotion)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) + 
  facet_wrap(~ Participant) +
  labs(title = "Reaction Time by Number of Distractors", 
       subtitle = "Per Subject", y = "Reaction time in Seconds")
```

```{r average-happy-vs-sad-rt}
recognition %>%
  group_by(Emotion) %>%
  summarize(mean_per_distractor = mean(Time))
```
The average RT of Happy was 1.65 seconds while Sad was 1.77 seconds, very very
similar. 

```{r make-mean-by-emotion-distrator-person}
mean_time_by_emotion_distractor_person <- recognition %>%
  group_by(Emotion, Distractors, Person) %>%
  summarize(mean = mean(Time))
```

```{r plot-mean-by-emotion-distrator-person-by-person}
mean_time_by_emotion_distractor_person %>%
  ggplot(mapping = aes(x = Distractors, y = mean, 
                                           color = Emotion)) +
  geom_point() +
 # geom_smooth(method = lm, se = FALSE) + 
  facet_wrap(~ Person) +
  labs(title = "Reaction Time by Number of Distractors", 
       subtitle = "All Subjects", y = "Reaction time in Seconds")
```

```{r}
recognition %>%
  group_by(Emotion, Distractors) %>%
  summarize(mean = mean(Time))
 # pull(mean)
```
average difference between happy/sad for each familiar face at each distraction level

Happy = output[1:4]
Sad = output[8:12]
Happy - Sad
